name: Manual OpenAPI Linting

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]


jobs:
  validate-openapi:
    name: Validate OpenAPI Specification
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli
        
      - name: Validate OpenAPI spec with Spectral
        run: |
          spectral lint api/openapi.yaml 