name: Lint Open API and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  api-linting:
    name: Run Spectral
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Run Spectral
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'api/*.yaml'

  generate-site:
    name: Generate API Reference
    runs-on: ubuntu-latest
    needs: api-linting
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 18 }

      - name: Redocly CLI Command
        run: npx @redocly/cli build-docs api/openapi.yaml -o api/reference.html
        
