# This is a basic workflow to help you get started with Actions

name: Vale-Linting

# Event to trigger when the action is run
on:
  # Tiggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale Check
      uses: errata-ai/vale-action@v2.1.1
      with:
        debug: true
        fail_on_error: true
        styles: |
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          https://github.com/errata-ai/Google/releases/latest/download/Google.zip
          https://github.com/errata-ai/Joblint/releases/download/v0.4.1/Joblint.zip
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
  